#!/usr/bin/env python3
"""
create_cnn_int8_notebook.py
Programmatically constructs CNN/train_1d_cnn_int8.ipynb using nbformat.
Enforces 100% INT8 Model Architecture with `use_bias=True` across all Conv1D and Dense layers.
"""

import os
import nbformat as nbf

def create_notebook():
    nb = nbf.v4.new_notebook()
    nb.metadata['language_info'] = {'name': 'python', 'version': '3.10'}
    
    cells = []
    
    # Title & Overview
    cells.append(nbf.v4.new_markdown_cell(
        "# Pure INT8 1D CNN Model Training & Microcontroller Export Pipeline\n"
        "\n"
        "This notebook trains a 1D Convolutional Neural Network (CNN) intraoperative risk prediction model "
        "configured with **`use_bias=True`** across all layers, exporting FULL INT8 TFLite models for Silicon Labs **EFR32 microcontrollers**.\n"
        "\n"
        "### Key Technical Features:\n"
        "1. **Full INT8 Quantization**: Input tensor is `int8_t`, output tensor is `int8_t`, and weights are `int8_t`.\n"
        "2. **Layer Biases (`use_bias=True`)**: Includes bias parameters in all `Conv1D` and `Dense` layers.\n"
        "3. **Zero Float Normalization**: Feature scaling is pre-computed into `int8_t` (`[-128, 127]`)."
    ))
    
    # Cell 0: Self-Healing Dependency Resolver
    cells.append(nbf.v4.new_markdown_cell("## 0. Environment & TensorFlow Check"))
    cell0_code = (
        "import sys, subprocess\n"
        "try:\n"
        "    import tensorflow as tf\n"
        "    from tensorflow.python import pywrap_tensorflow\n"
        "    print(f'[Kernel Check] TensorFlow v{tf.__version__} is correctly installed and ready.')\n"
        "except (ImportError, ModuleNotFoundError, AttributeError) as e:\n"
        "    print(f'[Kernel Warning] TensorFlow issue detected ({e}). Repairing package in current kernel...')\n"
        "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'tensorflow'])\n"
        "    import tensorflow as tf\n"
        "    print(f'[Kernel Success] TensorFlow successfully installed/repaired: v{tf.__version__}')"
    )
    cells.append(nbf.v4.new_code_cell(cell0_code))
    
    # Cell 1: CPU Parallelism Setup
    cells.append(nbf.v4.new_markdown_cell("## 1. CPU Environment & Parallelism Setup"))
    cell1_code = (
        "import os\n"
        "import glob\n"
        "import json\n"
        "import gc\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "\n"
        "os.environ['OMP_NUM_THREADS'] = '4'\n"
        "os.environ['MKL_NUM_THREADS'] = '4'\n"
        "\n"
        "import tensorflow as tf\n"
        "from tensorflow import keras\n"
        "from sklearn.model_selection import train_test_split\n"
        "from sklearn.utils.class_weight import compute_class_weight\n"
        "from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score\n"
        "\n"
        "tf.config.threading.set_inter_op_parallelism_threads(2)\n"
        "tf.config.threading.set_intra_op_parallelism_threads(4)\n"
        "\n"
        "MODEL_OUTPUT_DIR = 'models_int8'\n"
        "os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)\n"
        "print(f'[Setup] Dedicated storage initialized: {MODEL_OUTPUT_DIR}')"
    )
    cells.append(nbf.v4.new_code_cell(cell1_code))
    
    # Cell 2: Configuration & Dataset Indexing
    cells.append(nbf.v4.new_markdown_cell("## 2. Configuration & Dataset Indexing"))
    cell2_code = (
        "# --- Configuration & Hyperparameters ---\n"
        "WINDOW_SIZE = 600\n"
        "STRIDE = 10\n"
        "EPOCHS = 8\n"
        "BATCH_SIZE = 128\n"
        "MAX_TRAIN = 500\n"
        "MAX_VAL = 100\n"
        "MAX_WINDOWS_PER_PATIENT = 300\n"
        "\n"
        "possible_paths = [\n"
        "    '../process_labeled_data',\n"
        "    'process_labeled_data',\n"
        "    '/home/logan78/Desktop/SiLabs/process_labeled_data'\n"
        "]\n"
        "input_dir = next((p for p in possible_paths if os.path.exists(p)), 'process_labeled_data')\n"
        "csv_files = sorted(glob.glob(os.path.join(input_dir, 'patient_*_1hz.csv')))\n"
        "print(f'[Dataset] Found {len(csv_files)} patient records in: {input_dir}')\n"
        "\n"
        "base_features = [\n"
        "    'Solar8000/HR', 'Solar8000/ART_SBP', 'Solar8000/ART_DBP', 'Solar8000/ART_MBP',\n"
        "    'Solar8000/PLETH_SPO2', 'Solar8000/RR_CO2', 'Solar8000/ETCO2', 'Primus/FIO2', 'Solar8000/BT'\n"
        "]\n"
        "engineered_features = [\n"
        "    'Feature_Pulse_Pressure', 'Feature_Shock_Index', 'Feature_Modified_Shock_Index',\n"
        "    'Feature_Rate_Pressure_Product', 'Feature_HR_Mean_60s', 'Feature_HR_Std_60s',\n"
        "    'Feature_HR_Delta_60s', 'Feature_MBP_Mean_60s', 'Feature_MBP_Std_60s', 'Feature_MBP_Delta_60s'\n"
        "]\n"
        "features = base_features + engineered_features\n"
        "\n"
        "train_val_files, test_files = train_test_split(csv_files[:MAX_TRAIN + MAX_VAL], test_size=0.15, random_state=42, shuffle=True)\n"
        "train_files, val_files = train_test_split(train_val_files, test_size=0.15, random_state=42, shuffle=True)\n"
        "train_files = train_files[:MAX_TRAIN]\n"
        "val_files = val_files[:MAX_VAL]\n"
        "\n"
        "print(f'[Dataset Split] Train: {len(train_files)} patients | Val: {len(val_files)} patients | Test: {len(test_files)} patients')"
    )
    cells.append(nbf.v4.new_code_cell(cell2_code))
    
    # Cell 3: Feature Scaler Computation
    cells.append(nbf.v4.new_markdown_cell("## 3. INT8 Feature Scaler Parameters"))
    cell3_code = (
        "print('[INT8 Scaler] Computing global feature min/max and INT8 quantization parameters...')\n"
        "scaler_data = []\n"
        "for file in train_files[:200]:\n"
        "    try:\n"
        "        df = pd.read_csv(file, usecols=lambda c: c in features)\n"
        "        avail = [c for c in features if c in df.columns]\n"
        "        if len(avail) == len(features):\n"
        "            scaler_data.append(df[features].ffill().bfill().fillna(0).values.astype(np.float32))\n"
        "    except Exception:\n"
        "        continue\n"
        "\n"
        "stacked = np.vstack(scaler_data)\n"
        "feat_min = np.percentile(stacked, 0.1, axis=0)\n"
        "feat_max = np.percentile(stacked, 99.9, axis=0)\n"
        "feat_mean = np.mean(stacked, axis=0)\n"
        "feat_var = np.var(stacked, axis=0)\n"
        "\n"
        "del stacked, scaler_data\n"
        "gc.collect()\n"
        "\n"
        "int8_scale = (feat_max - feat_min) / 255.0\n"
        "int8_scale = np.where(int8_scale == 0, 1e-5, int8_scale)\n"
        "int8_zero_point = np.round(-128 - (feat_min / int8_scale)).astype(np.int32)\n"
        "int8_zero_point = np.clip(int8_zero_point, -128, 127)\n"
        "\n"
        "def float_to_int8(x_float):\n"
        "    q_val = np.round((x_float / int8_scale) + int8_zero_point)\n"
        "    return np.clip(q_val, -128, 127).astype(np.int8)\n"
        "\n"
        "def int8_to_float(x_int8):\n"
        "    return ((x_int8.astype(np.float32) - int8_zero_point) * int8_scale).astype(np.float32)\n"
        "\n"
        "scaler_dict = {\n"
        "    'features': features,\n"
        "    'int8_scale': {feat: float(int8_scale[i]) for i, feat in enumerate(features)},\n"
        "    'int8_zero_point': {feat: int(int8_zero_point[i]) for i, feat in enumerate(features)},\n"
        "    'min': {feat: float(feat_min[i]) for i, feat in enumerate(features)},\n"
        "    'max': {feat: float(feat_max[i]) for i, feat in enumerate(features)},\n"
        "    'mean': {feat: float(feat_mean[i]) for i, feat in enumerate(features)},\n"
        "    'variance': {feat: float(feat_var[i]) for i, feat in enumerate(features)}\n"
        "}\n"
        "\n"
        "scaler_json_path = os.path.join(MODEL_OUTPUT_DIR, 'scaler_1d_cnn_int8.json')\n"
        "with open(scaler_json_path, 'w') as f:\n"
        "    json.dump(scaler_dict, f, indent=4)\n"
        "print(f'[INT8 Scaler] Saved quantization parameters to: {scaler_json_path}')"
    )
    cells.append(nbf.v4.new_code_cell(cell3_code))
    
    # Cell 4: Data Generator & Keras Architecture (use_bias=True)
    cells.append(nbf.v4.new_markdown_cell("## 4. INT8 1D CNN Architecture (`use_bias=True`)"))
    cell4_code = (
        "class Int8WindowDataGenerator(keras.utils.Sequence):\n"
        "    def __init__(self, file_list, target_col, features, batch_size=128, window_size=600, stride=10, max_windows=300, shuffle=True):\n"
        "        self.batch_size = batch_size\n"
        "        self.window_size = window_size\n"
        "        self.stride = stride\n"
        "        self.shuffle = shuffle\n"
        "        self.X_int8 = []\n"
        "        self.y_data = []\n"
        "        self.window_indices = []\n"
        "        \n"
        "        for file_idx, file in enumerate(file_list):\n"
        "            try:\n"
        "                df = pd.read_csv(file, usecols=lambda c: c in features or c == target_col)\n"
        "                avail = [c for c in features if c in df.columns]\n"
        "                if len(avail) < len(features) or target_col not in df.columns:\n"
        "                    continue\n"
        "                df_sub = df[avail + [target_col]].ffill().bfill().fillna(0)\n"
        "                raw_float = df_sub[avail].values.astype(np.float32)\n"
        "                y_vals = df_sub[target_col].values.astype(np.float32)\n"
        "                arr_int8 = float_to_int8(raw_float)\n"
        "                self.X_int8.append(arr_int8)\n"
        "                self.y_data.append(y_vals)\n"
        "                \n"
        "                patient_wins = 0\n"
        "                for i in range(0, len(arr_int8) - window_size, stride):\n"
        "                    if not np.isnan(y_vals[i + window_size - 1]):\n"
        "                        self.window_indices.append((file_idx, i))\n"
        "                        patient_wins += 1\n"
        "                        if patient_wins >= max_windows:\n"
        "                            break\n"
        "            except Exception:\n"
        "                continue\n"
        "        self.indices = np.arange(len(self.window_indices))\n"
        "        if self.shuffle:\n"
        "            np.random.shuffle(self.indices)\n"
        "            \n"
        "    def __len__(self):\n"
        "        return int(np.ceil(len(self.window_indices) / self.batch_size))\n"
        "        \n"
        "    def __getitem__(self, idx):\n"
        "        batch_inds = self.indices[idx * self.batch_size : (idx + 1) * self.batch_size]\n"
        "        X_batch_int8 = np.empty((len(batch_inds), self.window_size, len(features)), dtype=np.int8)\n"
        "        y_batch = np.empty((len(batch_inds),), dtype=np.float32)\n"
        "        for i, b_idx in enumerate(batch_inds):\n"
        "            file_idx, start = self.window_indices[b_idx]\n"
        "            X_batch_int8[i] = self.X_int8[file_idx][start : start + self.window_size]\n"
        "            y_batch[i] = self.y_data[file_idx][start + self.window_size - 1]\n"
        "        return int8_to_float(X_batch_int8), y_batch\n"
        "        \n"
        "    def get_int8_sample_generator(self, num_samples=200):\n"
        "        indices = np.random.choice(len(self.window_indices), size=min(num_samples, len(self.window_indices)), replace=False)\n"
        "        for b_idx in indices:\n"
        "            file_idx, start = self.window_indices[b_idx]\n"
        "            sample_int8 = self.X_int8[file_idx][start : start + self.window_size]\n"
        "            yield int8_to_float(np.expand_dims(sample_int8, axis=0))\n"
        "        \n"
        "    def get_all_y(self):\n"
        "        y_all = np.empty(len(self.window_indices), dtype=np.float32)\n"
        "        for i, w_idx in enumerate(self.window_indices):\n"
        "            file_idx, start = w_idx\n"
        "            y_all[i] = self.y_data[file_idx][start + self.window_size - 1]\n"
        "        return y_all\n"
        "\n"
        "# 1D CNN Keras Architecture with Biases (use_bias=True)\n"
        "def get_compiled_model(target_name):\n"
        "    dropout_rate = 0.5 if target_name == 'Future_Hypoxia' else 0.3\n"
        "    inputs = keras.Input(shape=(WINDOW_SIZE, len(features)))\n"
        "    x = keras.layers.Conv1D(16, 5, strides=2, activation='relu', padding='same', use_bias=True, kernel_regularizer=keras.regularizers.l2(0.001))(inputs)\n"
        "    x = keras.layers.MaxPool1D(2)(x)\n"
        "    x = keras.layers.Conv1D(32, 5, strides=2, activation='relu', padding='same', use_bias=True, kernel_regularizer=keras.regularizers.l2(0.001))(x)\n"
        "    x = keras.layers.MaxPool1D(2)(x)\n"
        "    x = keras.layers.Conv1D(32, 5, strides=2, activation='relu', padding='same', use_bias=True, kernel_regularizer=keras.regularizers.l2(0.001))(x)\n"
        "    x = keras.layers.GlobalAveragePooling1D()(x)\n"
        "    x = keras.layers.Dropout(dropout_rate)(x)\n"
        "    outputs = keras.layers.Dense(1, activation='sigmoid', use_bias=True)(x)\n"
        "    model = keras.Model(inputs=inputs, outputs=outputs)\n"
        "    model.compile(\n"
        "        optimizer=keras.optimizers.Adam(learning_rate=0.001),\n"
        "        loss='binary_crossentropy',\n"
        "        metrics=[keras.metrics.AUC(name='auc'), keras.metrics.AUC(curve='PR', name='pr_auc')]\n"
        "    )\n"
        "    return model"
    )
    cells.append(nbf.v4.new_code_cell(cell4_code))
    
    # Cell 5: Training & Model Export Loop
    cells.append(nbf.v4.new_markdown_cell("## 5. Training Loop & INT8 TFLite Conversion"))
    cell5_code = (
        "targets = ['Future_Hypotension', 'Future_Hypoxia', 'Future_Tachycardia']\n"
        "exported_models = []\n"
        "evaluation_results = {}\n"
        "\n"
        "for target in targets:\n"
        "    print('=' * 65)\n"
        "    print(f' TRAINING INT8 1D CNN (WITH BIASES) FOR: {target}')\n"
        "    print('=' * 65)\n"
        "    \n"
        "    train_gen = Int8WindowDataGenerator(train_files, target, features, BATCH_SIZE, WINDOW_SIZE, STRIDE, MAX_WINDOWS_PER_PATIENT, shuffle=True)\n"
        "    val_gen = Int8WindowDataGenerator(val_files, target, features, BATCH_SIZE, WINDOW_SIZE, STRIDE, MAX_WINDOWS_PER_PATIENT, shuffle=False)\n"
        "    \n"
        "    if len(train_gen) == 0:\n"
        "        continue\n"
        "        \n"
        "    y_tr = train_gen.get_all_y()\n"
        "    classes = np.unique(y_tr)\n"
        "    weights = compute_class_weight('balanced', classes=classes, y=y_tr)\n"
        "    class_weights = dict(zip(classes, weights))\n"
        "    if 0 in class_weights:\n"
        "        class_weights[0] *= 1.5\n"
        "        \n"
        "    model = get_compiled_model(target)\n"
        "    early_stop = keras.callbacks.EarlyStopping(monitor='val_pr_auc', mode='max', patience=3, restore_best_weights=True)\n"
        "    \n"
        "    history = model.fit(\n"
        "        train_gen,\n"
        "        validation_data=val_gen,\n"
        "        epochs=EPOCHS,\n"
        "        class_weight=class_weights,\n"
        "        callbacks=[early_stop],\n"
        "        verbose=1\n"
        "    )\n"
        "    \n"
        "    # Compute Validation Performance Metrics\n"
        "    y_val_true = val_gen.get_all_y()\n"
        "    y_val_prob = model.predict(val_gen, verbose=0).flatten()\n"
        "    best_t, max_f1 = 0.5, 0.0\n"
        "    for t in np.arange(0.2, 0.8, 0.02):\n"
        "        f1 = f1_score(y_val_true, (y_val_prob > t).astype(int), zero_division=0)\n"
        "        if f1 > max_f1:\n"
        "            max_f1 = f1\n"
        "            best_t = t\n"
        "            \n"
        "    cm = confusion_matrix(y_val_true, (y_val_prob > best_t).astype(int))\n"
        "    evaluation_results[target] = {\n"
        "        'cm': cm, 'threshold': best_t, 'f1': max_f1,\n"
        "        'precision': precision_score(y_val_true, (y_val_prob > best_t).astype(int), zero_division=0),\n"
        "        'recall': recall_score(y_val_true, (y_val_prob > best_t).astype(int), zero_division=0)\n"
        "    }\n"
        "    \n"
        "    # FULL INT8 TFLite Converter Configuration\n"
        "    print(f'\\n[FULL INT8 Converter] Quantizing {target} model to FULL INT8...')\n"
        "    def rep_gen():\n"
        "        for sample in train_gen.get_int8_sample_generator(num_samples=150):\n"
        "            yield [sample]\n"
        "            \n"
        "    converter = tf.lite.TFLiteConverter.from_keras_model(model)\n"
        "    converter.optimizations = [tf.lite.Optimize.DEFAULT]\n"
        "    converter.representative_dataset = rep_gen\n"
        "    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]\n"
        "    converter.inference_input_type = tf.int8\n"
        "    converter.inference_output_type = tf.int8\n"
        "    \n"
        "    tflite_int8_model = converter.convert()\n"
        "    \n"
        "    # ON-NOTEBOOK VERIFICATION OF TENSORS\n"
        "    interpreter = tf.lite.Interpreter(model_content=tflite_int8_model)\n"
        "    interpreter.allocate_tensors()\n"
        "    inp_dtype = interpreter.get_input_details()[0]['dtype']\n"
        "    out_dtype = interpreter.get_output_details()[0]['dtype']\n"
        "    assert inp_dtype == np.int8, f'Input is {inp_dtype}, not int8!'\n"
        "    assert out_dtype == np.int8, f'Output is {out_dtype}, not int8!'\n"
        "    print(f'✓ VERIFIED: INT8 TFLite Model (Input: {inp_dtype}, Output: {out_dtype})')\n"
        "    \n"
        "    tflite_filename = f'cnn_int8_{target}.tflite'\n"
        "    tflite_full_path = os.path.join(MODEL_OUTPUT_DIR, tflite_filename)\n"
        "    with open(tflite_full_path, 'wb') as f:\n"
        "        f.write(tflite_int8_model)\n"
        "        \n"
        "    file_size_kb = len(tflite_int8_model) / 1024.0\n"
        "    exported_models.append((target, tflite_full_path, file_size_kb))\n"
        "    print(f'✓ Saved INT8 TFLite model: {tflite_full_path} ({file_size_kb:.2f} KB)')\n"
        "    \n"
        "    keras.backend.clear_session()\n"
        "    del train_gen, val_gen, y_tr, model\n"
        "    gc.collect()\n"
        "\n"
        "print('\\n' + '=' * 65)\n"
        "print('SUMMARY OF EXPORTED INT8 MODELS:')\n"
        "for target, path, size in exported_models:\n"
        "    print(f' - {target}: {path} ({size:.2f} KB)')\n"
        "print(f' - INT8 Scaler Parameters: {scaler_json_path}')\n"
        "print('=' * 65)"
    )
    cells.append(nbf.v4.new_code_cell(cell5_code))
    
    # Cell 6: Confusion Matrix Heatmap Visualization
    cells.append(nbf.v4.new_markdown_cell("## 6. Confusion Matrix Heatmaps"))
    cell6_code = (
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
        "fig.suptitle('INT8 1D CNN Validation Confusion Matrices', fontsize=14, fontweight='bold')\n"
        "\n"
        "target_titles = {\n"
        "    'Future_Hypotension': 'Hypotension (MAP < 65)',\n"
        "    'Future_Hypoxia': 'Hypoxia (SpO2 < 90)',\n"
        "    'Future_Tachycardia': 'Tachycardia (HR > 100)'\n"
        "}\n"
        "\n"
        "for idx, target in enumerate(targets):\n"
        "    ax = axes[idx]\n"
        "    if target in evaluation_results:\n"
        "        cm = evaluation_results[target]['cm']\n"
        "        thresh = evaluation_results[target]['threshold']\n"
        "        f1 = evaluation_results[target]['f1']\n"
        "        prec = evaluation_results[target]['precision']\n"
        "        rec = evaluation_results[target]['recall']\n"
        "        \n"
        "        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, cbar=False,\n"
        "                    xticklabels=['No Event', 'Adverse Event'],\n"
        "                    yticklabels=['No Event', 'Adverse Event'],\n"
        "                    annot_kws={'size': 14, 'weight': 'bold'})\n"
        "        ax.set_title(f'{target_titles[target]}\\n(Thresh: {thresh:.2f} | F1: {f1:.3f})', fontsize=12)\n"
        "        ax.set_xlabel(f'Predicted\\n(Prec: {prec:.2f} | Rec: {rec:.2f})', fontsize=11)\n"
        "        ax.set_ylabel('Actual Label', fontsize=11)\n"
        "    else:\n"
        "        ax.text(0.5, 0.5, 'No Data', ha='center', va='center')\n"
        "\n"
        "plt.tight_layout()\n"
        "cm_fig_path = os.path.join(MODEL_OUTPUT_DIR, 'confusion_matrices_int8.png')\n"
        "plt.savefig(cm_fig_path, dpi=300, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(f'[Confusion Matrix Plot] Saved heatmap figure to: {cm_fig_path}')"
    )
    cells.append(nbf.v4.new_code_cell(cell6_code))
    
    nb.cells = cells
    
    output_path = "CNN/train_1d_cnn_int8.ipynb"
    with open(output_path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
        
    print(f"Successfully generated INT8 notebook with biases: {output_path}")

if __name__ == "__main__":
    create_notebook()
