/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#00201d",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-container": "#73e0d2",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "primary-container": "#0f52ba",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-primary-fixed-variant": "#00419c",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#89f5e7",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#b0c6ff",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d3e4fe",
        "tertiary-container": "#00635b",
        "on-surface-variant": "#434653",
        "surface": "#f7f9fb",
        "outline-variant": "#c3c6d5",
        "outline": "#737784",
        "error-container": "#ffdad6",
        "primary": "#003c90",
        "primary-fixed": "#d9e2ff",
        "secondary-container": "#d0e1fb",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-container": "#54647a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "tertiary": "#004943",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#005049",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-container": "#bcceff",
        "secondary": "#505f76",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b0c6ff",
        "surface-tint": "#1d59c1",
        "on-primary-fixed": "#001945"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "24px",
        "gutter": "20px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "32px",
        "xl": "48px",
        "base": "4px"
      },
      fontFamily: {
        "display-vitals": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-vitals": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
